config/routes.rb
Rails.application.routes.draw do

  root "auctions#index"

  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  resources :auctions do
    resources :bids, only: [:new, :create]
    resources :close_auction, only: [:create]
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)

        can :manage, Auction do |auction|
            auction.user == user
        end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/auction.rb
class Auction < ActiveRecord::Base
  include AASM

  belongs_to :user
  has_many :bids, dependent: :destroy
  
  validates :title, presence: true
  validates :details, presence: true
  validates :ends_on, presence: true
  validates :reserved_price, numericality: true


  
  aasm do
    state :published, initial: true
    state :reserve_met
    state :won
    state :canceled
    state :reserve_not_met

    event :close do
      transitions from: :published, to: :reserve_met
    end

    event :auction_complete do
      transitions from: :reserve_met, to: :won
    end

    event :cancel do
      transitions from: :published, to: :canceled
    end

    event :auction_price_not_met do
      transitions from: :published, to: :reserve_not_met
    end
  end
end

app/models/bid.rb
class Bid < ActiveRecord::Base
  belongs_to :user
  belongs_to :auction

  #validates to make sure the current bid is greater than the current high bid
  validates :price, numericality: true 

  def self.highest_bid_so_far
    order(price: "DESC").first.price
  end 

  def self.order_by_highest
    order(price: "DESC")
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :bids, dependent: :destroy
  has_many :auctions, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find_by_id session[:user_id]
  end
  helper_method :current_user

  def user_signed_in?
    current_user.present?
  end

  def authenticate_user!
    redirect_to new_session_path, alert: "Please sign in" unless session[:user_id].present?
  end

end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy, :show]

  def index
    @auctions = Auction.all
  end

  def new
    @auction = Auction.new
  end

  def create
    @auction = current_user.auctions.new(auction_params)
    if @auction.save
      redirect_to auction_path(@auction), notice: "Auction Created"
    else
      render :new
      flash[:alert] = "Sorry...something went wrong"
    end
  end


  def show
    @auction = Auction.find params[:id]
    @bid = current_user.bids.new

    if @auction.bids.any?
      @bids = @auction.bids.order_by_highest
      @current_price = @auction.bids.highest_bid_so_far + 1
    end
  end


  def edit
    @auction = current_user.auctions.find params[:id]
  end


  def update
    @auction = current_user.auctions.find params[:id]
    if @auction.update(auction_params)
      redirect_to auction_path(@auction), notice: "Auction Updated"
    else
      render :edit
      flash[:alert] = "Sorry...something went wrong"
    end
  end


  def destroy
    @auction = current_user.auctions.find params[:id]
    @auction.destroy
    redirect_to auctions_path, alert: "Auction deleted"
  end

  private

  def auction_params
    params.require(:auction).permit(:title, :details, :ends_on, :reserved_price)
  end

end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
  before_action :authenticate_user!


  def create
    @auction = Auction.find params[:auction_id]
    @bid = current_user.bids.new(bid_params)
    @bid.auction = @auction
    
    respond_to do |format|
      if @auction.bids.any?
        @current_price = @auction.bids.highest_bid_so_far + 1
        if @bid.price <= @current_price
          format.html { redirect_to auction_path(@auction), alert: 
                    "Please make a bid greater than the current price"}
        else
          @bid.save
          format.html { redirect_to auction_path(@auction), notice: 
                                                      "Bid Created" }
          format.js { render }
        end
      else
        @current_price = @bid.price + 1
        @bid.save
        format.html { redirect_to auction_path(@auction) }
        format.js { render }
      end
    end
  end

  private

  def bid_params
    params.require(:bid).permit(:price)
  end 

end

app/controllers/close_auction_controller.rb
class CloseAuctionController < ApplicationController
  before_action :authenticate_user!

  def create
    auction = Auction.find params[:auction_id]
    auction.close
    if auction.save
      redirect_to auction, notice: "Auction Closed"
    else
      redirect_to auction, alert: "sorry..something went wrong"
    end

  end 
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  layout "external"

  def new
  end

  def create
    @user = User.find_by_email params[:email]
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_path, notice: "logged in successfully"
    else
      flash[:alert] = "Invalid username/password"
      redirect_to new_session_path
    end
  end


  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out successfully"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  layout "external"

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Created Account"
    else
      render :new
      flash[:alert] = "Sorry...something went wrong"
    end
  end

  #used to show all of the users auctions and bids they've made
  def show
    @user = User.find params[:id]
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auctions_helper.rb
module AuctionsHelper
end

app/helpers/bids_helper.rb
module BidsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/auctions/index.html.erb
<div class="container">
  <h1>Welcome To Biddr</h1>
  <% @auctions.each do |auction| %>
    <div class="well">
      <p>Title: <%= link_to auction.title, auction %></p>
      <p>Details: <%= auction.details %></p>
      <% if auction.ends_on %>
        <p>Ends On: <%= auction.ends_on %></p>
      <% end %>
      <% if auction.bids.any? %>
        <p>Current Price: $<%= auction.bids.highest_bid_so_far + 1 %></p>
      <% else %>
        <p>Current Price: No Bids Yet!</p>
      <% end %>
    </div>
  <% end %>
</div>

app/views/auctions/new.html.erb
<div class="sign-in-sign-up-forms">
  <div class="col-sm-12 col-md-6 col-md-offset-3">
    <div class="form-group">
      <h1>Create A New Auction:</h1>
      <br>
      <%= simple_form_for @auction do |f| %>
        <%= f.text_field :title, class: "form-control input-lg", placeholder: "title" %>
        <br>
        <%= f.text_area :details, class: "form-control input-lg", placeholder: "Details" %>
        <br>
        <%= f.text_field :reserved_price, class: "form-control input-lg", placeholder: "reserved price" %>
        <br>
        <%= f.datetime_field :ends_on, class: "form-controler input-lg", placeholder: "End Date" %>
        <br>
        <br>
        <%= f.submit "Create Auction", class: "btn btn-success btn-centered btn-lg" %>
      <% end %>
    <div>
  </div>
</div>

app/views/auctions/show.html.erb
<div class="container">

  <h2><%= @auction.title %></h2>
  <p>Details: <%= @auction.details %></p>
  <p>Reserved Price<%= @auction.reserved_price %></p>
  <p>Current Price: $<%= @current_price %></p>

  <% if @auction.published? %>
    <% if can? :manage, @auction %>
      <%= link_to "Reserve Price Met?", auction_close_auction_index_path(@auction), method: :post, class: "btn btn-danger" %> 
    <% end %>
  <% end %>

  <% if @auction.reserve_met? %>
    <h3>Sorry, this auction's reserve price has been met.</h3>
    <p>No More Bids Will Be Accepted</p>
  <% else %>
    <%# create a bid %>
      <% if cannot? :manage, @auction %>
        <h3>Create A Bid</h3>
        <%= simple_form_for @bid, url: auction_bids_path(@auction), remote: true do |f| %>
          <%= f.input :price, class: "form-control" %>
          <br>
          <%= f.submit "Create Bid", class: "btn btn-success" %>
        <% end %>
      <% else %>
        <p>Sorry..you can't bid on your own acutions</p>
      <% end %>
  <% end %>


  <% if @auction.bids.any? %>
    <p>Bids:</p> 
    <div class="bids">
      <% @bids.each do |bid| %>
                    <%= render partial: "/bids/bids", locals: {bid: bid} %>
               <% end %>
    </div>
  <% end %>

</div>

app/views/bids/_bids.html.erb
<div class="well">
  <%= bid.price %>
  <br>
  Bid By: <%= link_to bid.user.username, user_path(bid.user) %>
</div>

app/views/bids/create.js.erb
$(".bids").prepend("<%= j render partial: "/bids/bids", locals: {bid: @bid} %>");
$("#bid_price").val("");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BiddingApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <nav>
    <%= link_to "All Auctions", auctions_path %> |
    <%= link_to "New Auction", new_auction_path %> | 
    <% if current_user %>
      <%= link_to "Sign Out", sessions_path, method: :delete %>
    <% else %>
      <%= link_to "Sign In", new_session_path %> |
      <%= link_to "Sign Up", new_user_path %>
    <% end %>
  </nav>

  <% if flash[:notice] %>
    <div class="alert alert-success"><%= flash[:notice] %></div>
  <% elsif flash[:alert] %>
    <div class="alert alert-danger"><%= flash[:alert] %></div>
  <% end %>

  <%= yield %>
</div>

</body>
</html>

app/views/layouts/external.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Aocn</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  </head>
  <body>

    <div class="container">

      <%# flash messages %>
      <% if flash[:notice] %>
        <div class="alert alert-success"><%= flash[:notice] %></div>
      <% elsif flash[:alert] %>
        <div class="alert alert-danger"><%= flash[:alert] %></div>
      <% end %>

      <%# main content %>
      <%= yield %>

    <%# close main container %>
    </div>

  </body>
</html>

app/views/users/new.html.erb
<div class="sign-in-sign-up-forms">
  <div class="col-sm-12 col-md-6 col-md-offset-3">
    <div class="form-group">
      <h1>Welcome To Bidd.R!</h1>
      <p>Please create your account to login.</p>
      <br>
      <%= simple_form_for @user do |f| %>
        <%= f.text_field :username, class: "form-control input-lg", placeholder: "Username" %>
        <br>
        <%= f.text_field :email, class: "form-control input-lg", placeholder: "Email" %>
        <br>
        <%= f.password_field :password, class: "form-control input-lg", placeholder: "Password" %>
        <br>
        <%= f.password_field :password, class: "form-control input-lg", placeholder: "Confirm Password" %>
        <br>
        <%= f.submit "Create Account", class: "btn btn-success btn-centered" %>
      <% end %>
      <br>
      <%= link_to "Already made an account?", new_session_path %>
    <div>
  </div>
</div>

app/views/users/show.html.erb
<h1>Viewing Auctions and Bids for <%= @user.username %></h1>

<% @user.bids.each do |bid| %>
  <div class="well">
    <strong>Auction Name:</strong> <%= bid.auction.title %>
    <br> 
    <strong>Bid:</strong> <%= bid.price %>
  </div>
<% end %>